version: "2"
services:
    www:
        build: ./apache/
        ports:
            - 80:80
        volumes:
            - ./public_html:/var/www/html/
        links:
            - db
        networks:
            - default
        environment:
            DBUSER: root
            DBPASS: password
            DB: camagru
            DBHOST: db
        command: bash -c "chmod 777 . && exec /usr/sbin/apache2ctl -D FOREGROUND"
    db:
        image: mysql
        restart: always
        volumes:
        - persistent:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=password
        command: [
            'mysqld',
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: password
volumes:
    persistent:
